import type { Caption } from '@/data/types';

export function formatSrtTimecode(ms: number): string {
  const hours = Math.floor(ms / 3600000);
  const minutes = Math.floor((ms % 3600000) / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  const milliseconds = Math.floor(ms % 1000);

  return (
    `${hours.toString().padStart(2, '0')}:` +
    `${minutes.toString().padStart(2, '0')}:` +
    `${seconds.toString().padStart(2, '0')},` +
    `${milliseconds.toString().padStart(3, '0')}`
  );
}

export function captionsToSrt(captions: Caption[]): string {
  if (captions.length === 0) return '';

  const sorted = [...captions].sort((a, b) => a.startMs - b.startMs);

  return sorted
    .map((caption, index) => {
      const startTime = formatSrtTimecode(caption.startMs);
      const endTime = formatSrtTimecode(caption.endMs);
      const text = caption.text.trim();

      return `${index + 1}\n${startTime} --> ${endTime}\n${text}`;
    })
    .join('\n\n');
}

export function captionsToAss(captions: Caption[]): string {
  if (captions.length === 0) return '';

  const sorted = [...captions].sort((a, b) => a.startMs - b.startMs);

  const header = `[Script Info]
Title: Generated by VREW
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: 1280
PlayResY: 720
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,DejaVuSans,24,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const events = sorted
    .map((caption) => {
      const startTime = formatAssTimecode(caption.startMs);
      const endTime = formatAssTimecode(caption.endMs);
      const text = caption.text.trim();

      return `Dialogue: 0,${startTime},${endTime},Default,,0,0,0,,${text}`;
    })
    .join('\n');

  return header + events;
}

function formatAssTimecode(ms: number): string {
  const hours = Math.floor(ms / 3600000);
  const minutes = Math.floor((ms % 3600000) / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  const centiseconds = Math.floor((ms % 1000) / 10);

  return `${hours.toString().padStart(1, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}.${centiseconds.toString().padStart(2, '0')}`;
}

export function adjustSrtForTrim(
  captions: Caption[],
  trimStartMs: number,
  trimEndMs: number
): string {
  const filtered = captions.filter((c) => {
    return c.startMs < trimEndMs && c.endMs > trimStartMs;
  });

  const adjusted = filtered.map((c) => ({
    ...c,
    startMs: Math.max(0, c.startMs - trimStartMs),
    endMs: Math.min(trimEndMs - trimStartMs, c.endMs - trimStartMs),
  }));

  return captionsToSrt(adjusted);
}

export function adjustAssForTrim(
  captions: Caption[],
  trimStartMs: number,
  trimEndMs: number
): string {
  const filtered = captions.filter((c) => {
    return c.startMs < trimEndMs && c.endMs > trimStartMs;
  });

  const adjusted = filtered.map((c) => ({
    ...c,
    startMs: Math.max(0, c.startMs - trimStartMs),
    endMs: Math.min(trimEndMs - trimStartMs, c.endMs - trimStartMs),
  }));

  return captionsToAss(adjusted);
}
